from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 239)
        Dialog.setStyleSheet("background-color: rgb(195, 204, 191)")
        self.blackCam = QtWidgets.QPushButton(Dialog)
        self.blackCam.setGeometry(QtCore.QRect(50, 20, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        self.blackCam.setFont(font)
        self.blackCam.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.blackCam.setObjectName("blackCam")
        self.WhiteCam = QtWidgets.QPushButton(Dialog)
        self.WhiteCam.setGeometry(QtCore.QRect(240, 20, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        self.WhiteCam.setFont(font)
        self.WhiteCam.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.WhiteCam.setObjectName("WhiteCam")
        self.whitesubmit = QtWidgets.QPushButton(Dialog)
        self.whitesubmit.setGeometry(QtCore.QRect(260, 150, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        self.whitesubmit.setFont(font)
        self.whitesubmit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.whitesubmit.setObjectName("whitesubmit")
        self.blacksubmit = QtWidgets.QPushButton(Dialog)
        self.blacksubmit.setGeometry(QtCore.QRect(260, 180, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        self.blacksubmit.setFont(font)
        self.blacksubmit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.blacksubmit.setObjectName("blacksubmit")
        self.whitetext = QtWidgets.QTextEdit(Dialog)
        self.whitetext.setGeometry(QtCore.QRect(123, 140, 121, 31))
        self.whitetext.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.whitetext.setObjectName("whitetext")
        self.blacktext = QtWidgets.QPlainTextEdit(Dialog)
        self.blacktext.setGeometry(QtCore.QRect(123, 180, 121, 31))
        self.blacktext.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.blacktext.setObjectName("blacktext")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 149, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
                                 "")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 180, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.blackCam.setText(_translate("Dialog", "blackCam"))
        self.WhiteCam.setText(_translate("Dialog", "WhiteCam"))
        self.whitesubmit.setText(_translate("Dialog", "submit white"))
        self.blacksubmit.setText(_translate("Dialog", "submit black"))
        self.label.setText(_translate("Dialog", "White camera"))
        self.label_2.setText(_translate("Dialog", "Black camera"))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
